# Generated by Selenium IDE
import pytest

from fixture.application import Application
from model.group import Group


@pytest.fixture
def app(request):
    fixture = Application()
    request.addfinalizer(fixture.destroy)
    return fixture


def test_zadaniye2(app):
    app.login("admin", "secret")
    app.new_group_creation()
    app.fill_forms(Group("zadaniye2", "header2", "footer2"))
    app.submitting()
    app.return_to_group_page()
    app.logout()


def test_zadaniye2_empty(app):
    app.login("admin", "secret")
    app.new_group_creation()
    app.fill_forms(Group("", "", ""))
    app.submitting()
    app.return_to_group_page()
    app.logout()