# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

from application import Application
from group import Group


@pytest.fixture
def app(request):
    fixture = Application()
    request.addfinalizer(fixture.destroy)
    return fixture


def test_zadaniye2(app):
    app.login("admin", "secret")
    app.new_group_creation()
    app.fill_forms(Group("zadaniye2", "header2", "footer2"))
    app.submitting()
    app.return_to_group_page()
    app.logout()


def test_zadaniye2_empty(app):
    app.login("admin", "secret")
    app.new_group_creation()
    app.fill_forms(Group("", "", ""))
    app.submitting()
    app.return_to_group_page()
    app.logout()