# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities


class TestZadaniye1():
    def setup_method(self, method):
        self.wd = webdriver.Firefox()
        self.vars = {}

    def teardown_method(self, method):
        self.wd.quit()

    def test_zadaniye1(self):
        self.wd.get("http://localhost/addressbook/index.php")
        self.wd.set_window_size(1052, 839)
        self.wd.find_element(By.NAME, "user").send_keys("admin")
        self.wd.find_element(By.CSS_SELECTOR, "html").click()
        self.wd.find_element(By.NAME, "pass").click()
        self.wd.find_element(By.NAME, "pass").send_keys("secret")
        self.wd.find_element(By.CSS_SELECTOR, "input:nth-child(7)").click()
        self.wd.find_element(By.LINK_TEXT, "groups").click()
        self.wd.find_element(By.NAME, "new").click()
        self.wd.find_element(By.NAME, "group_name").click()
        self.wd.find_element(By.NAME, "group_name").send_keys("zadanye1")
        self.wd.find_element(By.NAME, "group_header").click()
        self.wd.find_element(By.NAME, "group_header").send_keys("me")
        self.wd.find_element(By.NAME, "group_footer").click()
        self.wd.find_element(By.NAME, "group_footer").send_keys("all")
        self.wd.find_element(By.NAME, "submit").click()
        self.wd.find_element(By.LINK_TEXT, "group page").click()
        self.wd.find_element(By.LINK_TEXT, "Logout").click()

