# Generated by Selenium IDE - Chrome version
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from selenium.webdriver.chrome.service import Service
from webdriver_manager.chrome import ChromeDriverManager
from contact import Contact


class TestTestzadaniye3():
    def setup_method(self, method):
        service = Service(ChromeDriverManager().install())
        self.driver = webdriver.Chrome(service=service)
        self.vars = {}
        self.driver.implicitly_wait(10)

    def teardown_method(self, method):
        self.driver.quit()

    def test_testzadaniye3(self):
        self.open_page()
        self.login("admin", "secret")
        self.new_contact()
        self.fill_contact(Contact("firstName", "middlename", "lastname", "nickname", "Pushkina", "88005553535", "88005553536","88005553537", "mail1.ru", "mail2.ru", "mail3.ru"))
        self.save_and_logout()

    def save_and_logout(self):
        self.driver.find_element(By.CSS_SELECTOR, "input:nth-child(71)").click()

        WebDriverWait(self.driver, 10).until(
            expected_conditions.presence_of_element_located((By.LINK_TEXT, "home"))
        ).click()

        self.driver.find_element(By.LINK_TEXT, "Logout").click()

    def fill_contact(self, Contact):
        self.driver.find_element(By.NAME, "firstname").click()
        self.driver.find_element(By.NAME, "firstname").clear()
        self.driver.find_element(By.NAME, "firstname").send_keys("%s" % Contact.firstname)

        self.driver.find_element(By.NAME, "middlename").click()
        self.driver.find_element(By.NAME, "middlename").clear()
        self.driver.find_element(By.NAME, "middlename").send_keys("%s" % Contact.middlename)

        self.driver.find_element(By.NAME, "lastname").click()
        self.driver.find_element(By.NAME, "lastname").clear()
        self.driver.find_element(By.NAME, "lastname").send_keys("%s" % Contact.lastname)

        self.driver.find_element(By.NAME, "nickname").click()
        self.driver.find_element(By.NAME, "nickname").clear()
        self.driver.find_element(By.NAME, "nickname").send_keys("%s" % Contact.nickname)

        self.driver.find_element(By.NAME, "address").click()
        self.driver.find_element(By.NAME, "address").clear()
        self.driver.find_element(By.NAME, "address").send_keys("%s" % Contact.adress)

        self.driver.find_element(By.NAME, "home").click()
        self.driver.find_element(By.NAME, "home").clear()
        self.driver.find_element(By.NAME, "home").send_keys("%s" % Contact.phone1)

        self.driver.find_element(By.NAME, "mobile").click()
        self.driver.find_element(By.NAME, "mobile").clear()
        self.driver.find_element(By.NAME, "mobile").send_keys("%s" % Contact.phone2)

        self.driver.find_element(By.NAME, "work").click()
        self.driver.find_element(By.NAME, "work").clear()
        self.driver.find_element(By.NAME, "work").send_keys("%s" % Contact.phone3)

        self.driver.find_element(By.NAME, "email").click()
        self.driver.find_element(By.NAME, "email").clear()
        self.driver.find_element(By.NAME, "email").send_keys("%s" % Contact.mail1)

        self.driver.find_element(By.NAME, "email2").click()
        self.driver.find_element(By.NAME, "email2").clear()
        self.driver.find_element(By.NAME, "email2").send_keys("%s" % Contact.mail2)

        self.driver.find_element(By.NAME, "email3").click()
        self.driver.find_element(By.NAME, "email3").clear()
        self.driver.find_element(By.NAME, "email3").send_keys("%s" % Contact.mail3)

    def new_contact(self):
        WebDriverWait(self.driver, 10).until(
            expected_conditions.presence_of_element_located((By.LINK_TEXT, "add new"))
        ).click()

    def login(self, login, password):
        self.driver.find_element(By.NAME, "user").send_keys("%s" % login)
        self.driver.find_element(By.NAME, "pass").click()
        self.driver.find_element(By.NAME, "pass").send_keys("%s" % password)
        self.driver.find_element(By.CSS_SELECTOR, "input:nth-child(7)").click()

    def open_page(self):
        self.driver.get("http://localhost/addressbook/index.php")
        self.driver.set_window_size(1202, 898)